/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _collision_h_
#define _collision_h_
//---------------------------------------------------------------------------------
extern const unsigned char collision[];
extern const int collision_size;
//---------------------------------------------------------------------------------
#endif //_collision_h_
//---------------------------------------------------------------------------------
