/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _movejunior_h_
#define _movejunior_h_
//---------------------------------------------------------------------------------
extern const unsigned char movejunior[];
extern const int movejunior_size;
//---------------------------------------------------------------------------------
#endif //_movejunior_h_
//---------------------------------------------------------------------------------
