/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _moveenemy_h_
#define _moveenemy_h_
//---------------------------------------------------------------------------------
extern const unsigned char moveenemy[];
extern const int moveenemy_size;
//---------------------------------------------------------------------------------
#endif //_moveenemy_h_
//---------------------------------------------------------------------------------
