/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _wrongjump_h_
#define _wrongjump_h_
//---------------------------------------------------------------------------------
extern const unsigned char wrongjump[];
extern const int wrongjump_size;
//---------------------------------------------------------------------------------
#endif //_wrongjump_h_
//---------------------------------------------------------------------------------
